// Generated by jextract

package org.maplibre.mlt.encoder.ffi;

import static java.lang.foreign.MemoryLayout.PathElement.*;
import static java.lang.foreign.ValueLayout.*;

import java.lang.foreign.*;
import java.lang.invoke.*;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

public class mlt_ffi_h extends mlt_ffi_h$shared {

  mlt_ffi_h() {
    // Should not be called directly
  }

  static final Arena LIBRARY_ARENA = Arena.ofAuto();

  static {
    System.loadLibrary("mlt_ffi");
  }

  static final SymbolLookup SYMBOL_LOOKUP =
      SymbolLookup.loaderLookup().or(Linker.nativeLinker().defaultLookup());

  private static class diplomat_buffer_write_create {
    public static final FunctionDescriptor DESC =
        FunctionDescriptor.of(mlt_ffi_h.C_POINTER, mlt_ffi_h.C_LONG);

    public static final MemorySegment ADDR =
        SYMBOL_LOOKUP.findOrThrow("diplomat_buffer_write_create");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * DiplomatWrite *diplomat_buffer_write_create(size_t cap)
   * }
   */
  public static FunctionDescriptor diplomat_buffer_write_create$descriptor() {
    return diplomat_buffer_write_create.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * DiplomatWrite *diplomat_buffer_write_create(size_t cap)
   * }
   */
  public static MethodHandle diplomat_buffer_write_create$handle() {
    return diplomat_buffer_write_create.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * DiplomatWrite *diplomat_buffer_write_create(size_t cap)
   * }
   */
  public static MemorySegment diplomat_buffer_write_create$address() {
    return diplomat_buffer_write_create.ADDR;
  }

  /**
   * {@snippet lang=c :
   * DiplomatWrite *diplomat_buffer_write_create(size_t cap)
   * }
   */
  public static MemorySegment diplomat_buffer_write_create(long cap) {
    var mh$ = diplomat_buffer_write_create.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("diplomat_buffer_write_create", cap);
      }
      return (MemorySegment) mh$.invokeExact(cap);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class diplomat_buffer_write_get_bytes {
    public static final FunctionDescriptor DESC =
        FunctionDescriptor.of(mlt_ffi_h.C_POINTER, mlt_ffi_h.C_POINTER);

    public static final MemorySegment ADDR =
        SYMBOL_LOOKUP.findOrThrow("diplomat_buffer_write_get_bytes");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * char *diplomat_buffer_write_get_bytes(DiplomatWrite *t)
   * }
   */
  public static FunctionDescriptor diplomat_buffer_write_get_bytes$descriptor() {
    return diplomat_buffer_write_get_bytes.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * char *diplomat_buffer_write_get_bytes(DiplomatWrite *t)
   * }
   */
  public static MethodHandle diplomat_buffer_write_get_bytes$handle() {
    return diplomat_buffer_write_get_bytes.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * char *diplomat_buffer_write_get_bytes(DiplomatWrite *t)
   * }
   */
  public static MemorySegment diplomat_buffer_write_get_bytes$address() {
    return diplomat_buffer_write_get_bytes.ADDR;
  }

  /**
   * {@snippet lang=c :
   * char *diplomat_buffer_write_get_bytes(DiplomatWrite *t)
   * }
   */
  public static MemorySegment diplomat_buffer_write_get_bytes(MemorySegment t) {
    var mh$ = diplomat_buffer_write_get_bytes.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("diplomat_buffer_write_get_bytes", t);
      }
      return (MemorySegment) mh$.invokeExact(t);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class diplomat_buffer_write_len {
    public static final FunctionDescriptor DESC =
        FunctionDescriptor.of(mlt_ffi_h.C_LONG, mlt_ffi_h.C_POINTER);

    public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("diplomat_buffer_write_len");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * size_t diplomat_buffer_write_len(DiplomatWrite *t)
   * }
   */
  public static FunctionDescriptor diplomat_buffer_write_len$descriptor() {
    return diplomat_buffer_write_len.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * size_t diplomat_buffer_write_len(DiplomatWrite *t)
   * }
   */
  public static MethodHandle diplomat_buffer_write_len$handle() {
    return diplomat_buffer_write_len.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * size_t diplomat_buffer_write_len(DiplomatWrite *t)
   * }
   */
  public static MemorySegment diplomat_buffer_write_len$address() {
    return diplomat_buffer_write_len.ADDR;
  }

  /**
   * {@snippet lang=c :
   * size_t diplomat_buffer_write_len(DiplomatWrite *t)
   * }
   */
  public static long diplomat_buffer_write_len(MemorySegment t) {
    var mh$ = diplomat_buffer_write_len.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("diplomat_buffer_write_len", t);
      }
      return (long) mh$.invokeExact(t);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class diplomat_buffer_write_destroy {
    public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(mlt_ffi_h.C_POINTER);

    public static final MemorySegment ADDR =
        SYMBOL_LOOKUP.findOrThrow("diplomat_buffer_write_destroy");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * void diplomat_buffer_write_destroy(DiplomatWrite *t)
   * }
   */
  public static FunctionDescriptor diplomat_buffer_write_destroy$descriptor() {
    return diplomat_buffer_write_destroy.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * void diplomat_buffer_write_destroy(DiplomatWrite *t)
   * }
   */
  public static MethodHandle diplomat_buffer_write_destroy$handle() {
    return diplomat_buffer_write_destroy.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * void diplomat_buffer_write_destroy(DiplomatWrite *t)
   * }
   */
  public static MemorySegment diplomat_buffer_write_destroy$address() {
    return diplomat_buffer_write_destroy.ADDR;
  }

  /**
   * {@snippet lang=c :
   * void diplomat_buffer_write_destroy(DiplomatWrite *t)
   * }
   */
  public static void diplomat_buffer_write_destroy(MemorySegment t) {
    var mh$ = diplomat_buffer_write_destroy.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("diplomat_buffer_write_destroy", t);
      }
      mh$.invokeExact(t);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static final int MltColumnType_Bool = (int) 0L;

  /**
   * {@snippet lang=c :
   * enum MltColumnType.MltColumnType_Bool = 0
   * }
   */
  public static int MltColumnType_Bool() {
    return MltColumnType_Bool;
  }

  private static final int MltColumnType_I8 = (int) 1L;

  /**
   * {@snippet lang=c :
   * enum MltColumnType.MltColumnType_I8 = 1
   * }
   */
  public static int MltColumnType_I8() {
    return MltColumnType_I8;
  }

  private static final int MltColumnType_U8 = (int) 2L;

  /**
   * {@snippet lang=c :
   * enum MltColumnType.MltColumnType_U8 = 2
   * }
   */
  public static int MltColumnType_U8() {
    return MltColumnType_U8;
  }

  private static final int MltColumnType_I32 = (int) 3L;

  /**
   * {@snippet lang=c :
   * enum MltColumnType.MltColumnType_I32 = 3
   * }
   */
  public static int MltColumnType_I32() {
    return MltColumnType_I32;
  }

  private static final int MltColumnType_U32 = (int) 4L;

  /**
   * {@snippet lang=c :
   * enum MltColumnType.MltColumnType_U32 = 4
   * }
   */
  public static int MltColumnType_U32() {
    return MltColumnType_U32;
  }

  private static final int MltColumnType_I64 = (int) 5L;

  /**
   * {@snippet lang=c :
   * enum MltColumnType.MltColumnType_I64 = 5
   * }
   */
  public static int MltColumnType_I64() {
    return MltColumnType_I64;
  }

  private static final int MltColumnType_U64 = (int) 6L;

  /**
   * {@snippet lang=c :
   * enum MltColumnType.MltColumnType_U64 = 6
   * }
   */
  public static int MltColumnType_U64() {
    return MltColumnType_U64;
  }

  private static final int MltColumnType_F32 = (int) 7L;

  /**
   * {@snippet lang=c :
   * enum MltColumnType.MltColumnType_F32 = 7
   * }
   */
  public static int MltColumnType_F32() {
    return MltColumnType_F32;
  }

  private static final int MltColumnType_F64 = (int) 8L;

  /**
   * {@snippet lang=c :
   * enum MltColumnType.MltColumnType_F64 = 8
   * }
   */
  public static int MltColumnType_F64() {
    return MltColumnType_F64;
  }

  private static class MltEncoderConfig_new_default {
    public static final FunctionDescriptor DESC = FunctionDescriptor.of(mlt_ffi_h.C_POINTER);

    public static final MemorySegment ADDR =
        SYMBOL_LOOKUP.findOrThrow("MltEncoderConfig_new_default");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * MltEncoderConfig *MltEncoderConfig_new_default()
   * }
   */
  public static FunctionDescriptor MltEncoderConfig_new_default$descriptor() {
    return MltEncoderConfig_new_default.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * MltEncoderConfig *MltEncoderConfig_new_default()
   * }
   */
  public static MethodHandle MltEncoderConfig_new_default$handle() {
    return MltEncoderConfig_new_default.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * MltEncoderConfig *MltEncoderConfig_new_default()
   * }
   */
  public static MemorySegment MltEncoderConfig_new_default$address() {
    return MltEncoderConfig_new_default.ADDR;
  }

  /**
   * {@snippet lang=c :
   * MltEncoderConfig *MltEncoderConfig_new_default()
   * }
   */
  public static MemorySegment MltEncoderConfig_new_default() {
    var mh$ = MltEncoderConfig_new_default.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("MltEncoderConfig_new_default");
      }
      return (MemorySegment) mh$.invokeExact();
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class MltEncoderConfig_set_tessellate {
    public static final FunctionDescriptor DESC =
        FunctionDescriptor.ofVoid(mlt_ffi_h.C_POINTER, mlt_ffi_h.C_BOOL);

    public static final MemorySegment ADDR =
        SYMBOL_LOOKUP.findOrThrow("MltEncoderConfig_set_tessellate");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * void MltEncoderConfig_set_tessellate(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static FunctionDescriptor MltEncoderConfig_set_tessellate$descriptor() {
    return MltEncoderConfig_set_tessellate.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * void MltEncoderConfig_set_tessellate(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static MethodHandle MltEncoderConfig_set_tessellate$handle() {
    return MltEncoderConfig_set_tessellate.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * void MltEncoderConfig_set_tessellate(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static MemorySegment MltEncoderConfig_set_tessellate$address() {
    return MltEncoderConfig_set_tessellate.ADDR;
  }

  /**
   * {@snippet lang=c :
   * void MltEncoderConfig_set_tessellate(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static void MltEncoderConfig_set_tessellate(MemorySegment self, boolean value) {
    var mh$ = MltEncoderConfig_set_tessellate.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("MltEncoderConfig_set_tessellate", self, value);
      }
      mh$.invokeExact(self, value);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class MltEncoderConfig_set_try_morton_sort {
    public static final FunctionDescriptor DESC =
        FunctionDescriptor.ofVoid(mlt_ffi_h.C_POINTER, mlt_ffi_h.C_BOOL);

    public static final MemorySegment ADDR =
        SYMBOL_LOOKUP.findOrThrow("MltEncoderConfig_set_try_morton_sort");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * void MltEncoderConfig_set_try_morton_sort(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static FunctionDescriptor MltEncoderConfig_set_try_morton_sort$descriptor() {
    return MltEncoderConfig_set_try_morton_sort.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * void MltEncoderConfig_set_try_morton_sort(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static MethodHandle MltEncoderConfig_set_try_morton_sort$handle() {
    return MltEncoderConfig_set_try_morton_sort.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * void MltEncoderConfig_set_try_morton_sort(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static MemorySegment MltEncoderConfig_set_try_morton_sort$address() {
    return MltEncoderConfig_set_try_morton_sort.ADDR;
  }

  /**
   * {@snippet lang=c :
   * void MltEncoderConfig_set_try_morton_sort(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static void MltEncoderConfig_set_try_morton_sort(MemorySegment self, boolean value) {
    var mh$ = MltEncoderConfig_set_try_morton_sort.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("MltEncoderConfig_set_try_morton_sort", self, value);
      }
      mh$.invokeExact(self, value);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class MltEncoderConfig_set_try_hilbert_sort {
    public static final FunctionDescriptor DESC =
        FunctionDescriptor.ofVoid(mlt_ffi_h.C_POINTER, mlt_ffi_h.C_BOOL);

    public static final MemorySegment ADDR =
        SYMBOL_LOOKUP.findOrThrow("MltEncoderConfig_set_try_hilbert_sort");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * void MltEncoderConfig_set_try_hilbert_sort(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static FunctionDescriptor MltEncoderConfig_set_try_hilbert_sort$descriptor() {
    return MltEncoderConfig_set_try_hilbert_sort.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * void MltEncoderConfig_set_try_hilbert_sort(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static MethodHandle MltEncoderConfig_set_try_hilbert_sort$handle() {
    return MltEncoderConfig_set_try_hilbert_sort.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * void MltEncoderConfig_set_try_hilbert_sort(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static MemorySegment MltEncoderConfig_set_try_hilbert_sort$address() {
    return MltEncoderConfig_set_try_hilbert_sort.ADDR;
  }

  /**
   * {@snippet lang=c :
   * void MltEncoderConfig_set_try_hilbert_sort(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static void MltEncoderConfig_set_try_hilbert_sort(MemorySegment self, boolean value) {
    var mh$ = MltEncoderConfig_set_try_hilbert_sort.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("MltEncoderConfig_set_try_hilbert_sort", self, value);
      }
      mh$.invokeExact(self, value);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class MltEncoderConfig_set_try_id_sort {
    public static final FunctionDescriptor DESC =
        FunctionDescriptor.ofVoid(mlt_ffi_h.C_POINTER, mlt_ffi_h.C_BOOL);

    public static final MemorySegment ADDR =
        SYMBOL_LOOKUP.findOrThrow("MltEncoderConfig_set_try_id_sort");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * void MltEncoderConfig_set_try_id_sort(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static FunctionDescriptor MltEncoderConfig_set_try_id_sort$descriptor() {
    return MltEncoderConfig_set_try_id_sort.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * void MltEncoderConfig_set_try_id_sort(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static MethodHandle MltEncoderConfig_set_try_id_sort$handle() {
    return MltEncoderConfig_set_try_id_sort.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * void MltEncoderConfig_set_try_id_sort(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static MemorySegment MltEncoderConfig_set_try_id_sort$address() {
    return MltEncoderConfig_set_try_id_sort.ADDR;
  }

  /**
   * {@snippet lang=c :
   * void MltEncoderConfig_set_try_id_sort(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static void MltEncoderConfig_set_try_id_sort(MemorySegment self, boolean value) {
    var mh$ = MltEncoderConfig_set_try_id_sort.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("MltEncoderConfig_set_try_id_sort", self, value);
      }
      mh$.invokeExact(self, value);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class MltEncoderConfig_set_allow_fsst {
    public static final FunctionDescriptor DESC =
        FunctionDescriptor.ofVoid(mlt_ffi_h.C_POINTER, mlt_ffi_h.C_BOOL);

    public static final MemorySegment ADDR =
        SYMBOL_LOOKUP.findOrThrow("MltEncoderConfig_set_allow_fsst");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * void MltEncoderConfig_set_allow_fsst(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static FunctionDescriptor MltEncoderConfig_set_allow_fsst$descriptor() {
    return MltEncoderConfig_set_allow_fsst.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * void MltEncoderConfig_set_allow_fsst(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static MethodHandle MltEncoderConfig_set_allow_fsst$handle() {
    return MltEncoderConfig_set_allow_fsst.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * void MltEncoderConfig_set_allow_fsst(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static MemorySegment MltEncoderConfig_set_allow_fsst$address() {
    return MltEncoderConfig_set_allow_fsst.ADDR;
  }

  /**
   * {@snippet lang=c :
   * void MltEncoderConfig_set_allow_fsst(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static void MltEncoderConfig_set_allow_fsst(MemorySegment self, boolean value) {
    var mh$ = MltEncoderConfig_set_allow_fsst.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("MltEncoderConfig_set_allow_fsst", self, value);
      }
      mh$.invokeExact(self, value);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class MltEncoderConfig_set_allow_fast_pfor {
    public static final FunctionDescriptor DESC =
        FunctionDescriptor.ofVoid(mlt_ffi_h.C_POINTER, mlt_ffi_h.C_BOOL);

    public static final MemorySegment ADDR =
        SYMBOL_LOOKUP.findOrThrow("MltEncoderConfig_set_allow_fast_pfor");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * void MltEncoderConfig_set_allow_fast_pfor(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static FunctionDescriptor MltEncoderConfig_set_allow_fast_pfor$descriptor() {
    return MltEncoderConfig_set_allow_fast_pfor.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * void MltEncoderConfig_set_allow_fast_pfor(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static MethodHandle MltEncoderConfig_set_allow_fast_pfor$handle() {
    return MltEncoderConfig_set_allow_fast_pfor.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * void MltEncoderConfig_set_allow_fast_pfor(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static MemorySegment MltEncoderConfig_set_allow_fast_pfor$address() {
    return MltEncoderConfig_set_allow_fast_pfor.ADDR;
  }

  /**
   * {@snippet lang=c :
   * void MltEncoderConfig_set_allow_fast_pfor(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static void MltEncoderConfig_set_allow_fast_pfor(MemorySegment self, boolean value) {
    var mh$ = MltEncoderConfig_set_allow_fast_pfor.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("MltEncoderConfig_set_allow_fast_pfor", self, value);
      }
      mh$.invokeExact(self, value);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class MltEncoderConfig_set_allow_shared_dict {
    public static final FunctionDescriptor DESC =
        FunctionDescriptor.ofVoid(mlt_ffi_h.C_POINTER, mlt_ffi_h.C_BOOL);

    public static final MemorySegment ADDR =
        SYMBOL_LOOKUP.findOrThrow("MltEncoderConfig_set_allow_shared_dict");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * void MltEncoderConfig_set_allow_shared_dict(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static FunctionDescriptor MltEncoderConfig_set_allow_shared_dict$descriptor() {
    return MltEncoderConfig_set_allow_shared_dict.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * void MltEncoderConfig_set_allow_shared_dict(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static MethodHandle MltEncoderConfig_set_allow_shared_dict$handle() {
    return MltEncoderConfig_set_allow_shared_dict.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * void MltEncoderConfig_set_allow_shared_dict(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static MemorySegment MltEncoderConfig_set_allow_shared_dict$address() {
    return MltEncoderConfig_set_allow_shared_dict.ADDR;
  }

  /**
   * {@snippet lang=c :
   * void MltEncoderConfig_set_allow_shared_dict(MltEncoderConfig *self, _Bool value)
   * }
   */
  public static void MltEncoderConfig_set_allow_shared_dict(MemorySegment self, boolean value) {
    var mh$ = MltEncoderConfig_set_allow_shared_dict.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("MltEncoderConfig_set_allow_shared_dict", self, value);
      }
      mh$.invokeExact(self, value);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class MltEncoderConfig_destroy {
    public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(mlt_ffi_h.C_POINTER);

    public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("MltEncoderConfig_destroy");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * void MltEncoderConfig_destroy(MltEncoderConfig *self)
   * }
   */
  public static FunctionDescriptor MltEncoderConfig_destroy$descriptor() {
    return MltEncoderConfig_destroy.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * void MltEncoderConfig_destroy(MltEncoderConfig *self)
   * }
   */
  public static MethodHandle MltEncoderConfig_destroy$handle() {
    return MltEncoderConfig_destroy.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * void MltEncoderConfig_destroy(MltEncoderConfig *self)
   * }
   */
  public static MemorySegment MltEncoderConfig_destroy$address() {
    return MltEncoderConfig_destroy.ADDR;
  }

  /**
   * {@snippet lang=c :
   * void MltEncoderConfig_destroy(MltEncoderConfig *self)
   * }
   */
  public static void MltEncoderConfig_destroy(MemorySegment self) {
    var mh$ = MltEncoderConfig_destroy.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("MltEncoderConfig_destroy", self);
      }
      mh$.invokeExact(self);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class MltEncodedBuffer_as_bytes {
    public static final FunctionDescriptor DESC =
        FunctionDescriptor.of(DiplomatU8View.layout(), mlt_ffi_h.C_POINTER);

    public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("MltEncodedBuffer_as_bytes");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * DiplomatU8View MltEncodedBuffer_as_bytes(const MltEncodedBuffer *self)
   * }
   */
  public static FunctionDescriptor MltEncodedBuffer_as_bytes$descriptor() {
    return MltEncodedBuffer_as_bytes.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * DiplomatU8View MltEncodedBuffer_as_bytes(const MltEncodedBuffer *self)
   * }
   */
  public static MethodHandle MltEncodedBuffer_as_bytes$handle() {
    return MltEncodedBuffer_as_bytes.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * DiplomatU8View MltEncodedBuffer_as_bytes(const MltEncodedBuffer *self)
   * }
   */
  public static MemorySegment MltEncodedBuffer_as_bytes$address() {
    return MltEncodedBuffer_as_bytes.ADDR;
  }

  /**
   * {@snippet lang=c :
   * DiplomatU8View MltEncodedBuffer_as_bytes(const MltEncodedBuffer *self)
   * }
   */
  public static MemorySegment MltEncodedBuffer_as_bytes(
      SegmentAllocator allocator, MemorySegment self) {
    var mh$ = MltEncodedBuffer_as_bytes.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("MltEncodedBuffer_as_bytes", allocator, self);
      }
      return (MemorySegment) mh$.invokeExact(allocator, self);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class MltEncodedBuffer_len {
    public static final FunctionDescriptor DESC =
        FunctionDescriptor.of(mlt_ffi_h.C_LONG, mlt_ffi_h.C_POINTER);

    public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("MltEncodedBuffer_len");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * size_t MltEncodedBuffer_len(const MltEncodedBuffer *self)
   * }
   */
  public static FunctionDescriptor MltEncodedBuffer_len$descriptor() {
    return MltEncodedBuffer_len.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * size_t MltEncodedBuffer_len(const MltEncodedBuffer *self)
   * }
   */
  public static MethodHandle MltEncodedBuffer_len$handle() {
    return MltEncodedBuffer_len.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * size_t MltEncodedBuffer_len(const MltEncodedBuffer *self)
   * }
   */
  public static MemorySegment MltEncodedBuffer_len$address() {
    return MltEncodedBuffer_len.ADDR;
  }

  /**
   * {@snippet lang=c :
   * size_t MltEncodedBuffer_len(const MltEncodedBuffer *self)
   * }
   */
  public static long MltEncodedBuffer_len(MemorySegment self) {
    var mh$ = MltEncodedBuffer_len.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("MltEncodedBuffer_len", self);
      }
      return (long) mh$.invokeExact(self);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class MltEncodedBuffer_is_empty {
    public static final FunctionDescriptor DESC =
        FunctionDescriptor.of(mlt_ffi_h.C_BOOL, mlt_ffi_h.C_POINTER);

    public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("MltEncodedBuffer_is_empty");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * _Bool MltEncodedBuffer_is_empty(const MltEncodedBuffer *self)
   * }
   */
  public static FunctionDescriptor MltEncodedBuffer_is_empty$descriptor() {
    return MltEncodedBuffer_is_empty.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * _Bool MltEncodedBuffer_is_empty(const MltEncodedBuffer *self)
   * }
   */
  public static MethodHandle MltEncodedBuffer_is_empty$handle() {
    return MltEncodedBuffer_is_empty.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * _Bool MltEncodedBuffer_is_empty(const MltEncodedBuffer *self)
   * }
   */
  public static MemorySegment MltEncodedBuffer_is_empty$address() {
    return MltEncodedBuffer_is_empty.ADDR;
  }

  /**
   * {@snippet lang=c :
   * _Bool MltEncodedBuffer_is_empty(const MltEncodedBuffer *self)
   * }
   */
  public static boolean MltEncodedBuffer_is_empty(MemorySegment self) {
    var mh$ = MltEncodedBuffer_is_empty.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("MltEncodedBuffer_is_empty", self);
      }
      return (boolean) mh$.invokeExact(self);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class MltEncodedBuffer_destroy {
    public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(mlt_ffi_h.C_POINTER);

    public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("MltEncodedBuffer_destroy");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * void MltEncodedBuffer_destroy(MltEncodedBuffer *self)
   * }
   */
  public static FunctionDescriptor MltEncodedBuffer_destroy$descriptor() {
    return MltEncodedBuffer_destroy.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * void MltEncodedBuffer_destroy(MltEncodedBuffer *self)
   * }
   */
  public static MethodHandle MltEncodedBuffer_destroy$handle() {
    return MltEncodedBuffer_destroy.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * void MltEncodedBuffer_destroy(MltEncodedBuffer *self)
   * }
   */
  public static MemorySegment MltEncodedBuffer_destroy$address() {
    return MltEncodedBuffer_destroy.ADDR;
  }

  /**
   * {@snippet lang=c :
   * void MltEncodedBuffer_destroy(MltEncodedBuffer *self)
   * }
   */
  public static void MltEncodedBuffer_destroy(MemorySegment self) {
    var mh$ = MltEncodedBuffer_destroy.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("MltEncodedBuffer_destroy", self);
      }
      mh$.invokeExact(self);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class MltError_message {
    public static final FunctionDescriptor DESC =
        FunctionDescriptor.ofVoid(mlt_ffi_h.C_POINTER, mlt_ffi_h.C_POINTER);

    public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("MltError_message");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * void MltError_message(const MltError *self, DiplomatWrite *write)
   * }
   */
  public static FunctionDescriptor MltError_message$descriptor() {
    return MltError_message.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * void MltError_message(const MltError *self, DiplomatWrite *write)
   * }
   */
  public static MethodHandle MltError_message$handle() {
    return MltError_message.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * void MltError_message(const MltError *self, DiplomatWrite *write)
   * }
   */
  public static MemorySegment MltError_message$address() {
    return MltError_message.ADDR;
  }

  /**
   * {@snippet lang=c :
   * void MltError_message(const MltError *self, DiplomatWrite *write)
   * }
   */
  public static void MltError_message(MemorySegment self, MemorySegment write) {
    var mh$ = MltError_message.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("MltError_message", self, write);
      }
      mh$.invokeExact(self, write);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class MltError_destroy {
    public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(mlt_ffi_h.C_POINTER);

    public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("MltError_destroy");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * void MltError_destroy(MltError *self)
   * }
   */
  public static FunctionDescriptor MltError_destroy$descriptor() {
    return MltError_destroy.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * void MltError_destroy(MltError *self)
   * }
   */
  public static MethodHandle MltError_destroy$handle() {
    return MltError_destroy.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * void MltError_destroy(MltError *self)
   * }
   */
  public static MemorySegment MltError_destroy$address() {
    return MltError_destroy.ADDR;
  }

  /**
   * {@snippet lang=c :
   * void MltError_destroy(MltError *self)
   * }
   */
  public static void MltError_destroy(MemorySegment self) {
    var mh$ = MltError_destroy.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("MltError_destroy", self);
      }
      mh$.invokeExact(self);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class MltLayerEncoder_new {
    public static final FunctionDescriptor DESC =
        FunctionDescriptor.of(
            MltLayerEncoder_new_result.layout(), DiplomatStringView.layout(), mlt_ffi_h.C_INT);

    public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("MltLayerEncoder_new");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * MltLayerEncoder_new_result MltLayerEncoder_new(DiplomatStringView name, uint32_t extent)
   * }
   */
  public static FunctionDescriptor MltLayerEncoder_new$descriptor() {
    return MltLayerEncoder_new.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * MltLayerEncoder_new_result MltLayerEncoder_new(DiplomatStringView name, uint32_t extent)
   * }
   */
  public static MethodHandle MltLayerEncoder_new$handle() {
    return MltLayerEncoder_new.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * MltLayerEncoder_new_result MltLayerEncoder_new(DiplomatStringView name, uint32_t extent)
   * }
   */
  public static MemorySegment MltLayerEncoder_new$address() {
    return MltLayerEncoder_new.ADDR;
  }

  /**
   * {@snippet lang=c :
   * MltLayerEncoder_new_result MltLayerEncoder_new(DiplomatStringView name, uint32_t extent)
   * }
   */
  public static MemorySegment MltLayerEncoder_new(
      SegmentAllocator allocator, MemorySegment name, int extent) {
    var mh$ = MltLayerEncoder_new.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("MltLayerEncoder_new", allocator, name, extent);
      }
      return (MemorySegment) mh$.invokeExact(allocator, name, extent);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class MltLayerEncoder_set_ids {
    public static final FunctionDescriptor DESC =
        FunctionDescriptor.of(
            MltLayerEncoder_set_ids_result.layout(),
            mlt_ffi_h.C_POINTER,
            DiplomatU64View.layout(),
            DiplomatBoolView.layout());

    public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("MltLayerEncoder_set_ids");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * MltLayerEncoder_set_ids_result MltLayerEncoder_set_ids(MltLayerEncoder *self, DiplomatU64View ids, DiplomatBoolView present)
   * }
   */
  public static FunctionDescriptor MltLayerEncoder_set_ids$descriptor() {
    return MltLayerEncoder_set_ids.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * MltLayerEncoder_set_ids_result MltLayerEncoder_set_ids(MltLayerEncoder *self, DiplomatU64View ids, DiplomatBoolView present)
   * }
   */
  public static MethodHandle MltLayerEncoder_set_ids$handle() {
    return MltLayerEncoder_set_ids.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * MltLayerEncoder_set_ids_result MltLayerEncoder_set_ids(MltLayerEncoder *self, DiplomatU64View ids, DiplomatBoolView present)
   * }
   */
  public static MemorySegment MltLayerEncoder_set_ids$address() {
    return MltLayerEncoder_set_ids.ADDR;
  }

  /**
   * {@snippet lang=c :
   * MltLayerEncoder_set_ids_result MltLayerEncoder_set_ids(MltLayerEncoder *self, DiplomatU64View ids, DiplomatBoolView present)
   * }
   */
  public static MemorySegment MltLayerEncoder_set_ids(
      SegmentAllocator allocator, MemorySegment self, MemorySegment ids, MemorySegment present) {
    var mh$ = MltLayerEncoder_set_ids.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("MltLayerEncoder_set_ids", allocator, self, ids, present);
      }
      return (MemorySegment) mh$.invokeExact(allocator, self, ids, present);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class MltLayerEncoder_set_geometries {
    public static final FunctionDescriptor DESC =
        FunctionDescriptor.of(
            MltLayerEncoder_set_geometries_result.layout(),
            mlt_ffi_h.C_POINTER,
            DiplomatI32View.layout(),
            DiplomatU32View.layout());

    public static final MemorySegment ADDR =
        SYMBOL_LOOKUP.findOrThrow("MltLayerEncoder_set_geometries");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * MltLayerEncoder_set_geometries_result MltLayerEncoder_set_geometries(MltLayerEncoder *self, DiplomatI32View coords, DiplomatU32View meta)
   * }
   */
  public static FunctionDescriptor MltLayerEncoder_set_geometries$descriptor() {
    return MltLayerEncoder_set_geometries.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * MltLayerEncoder_set_geometries_result MltLayerEncoder_set_geometries(MltLayerEncoder *self, DiplomatI32View coords, DiplomatU32View meta)
   * }
   */
  public static MethodHandle MltLayerEncoder_set_geometries$handle() {
    return MltLayerEncoder_set_geometries.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * MltLayerEncoder_set_geometries_result MltLayerEncoder_set_geometries(MltLayerEncoder *self, DiplomatI32View coords, DiplomatU32View meta)
   * }
   */
  public static MemorySegment MltLayerEncoder_set_geometries$address() {
    return MltLayerEncoder_set_geometries.ADDR;
  }

  /**
   * {@snippet lang=c :
   * MltLayerEncoder_set_geometries_result MltLayerEncoder_set_geometries(MltLayerEncoder *self, DiplomatI32View coords, DiplomatU32View meta)
   * }
   */
  public static MemorySegment MltLayerEncoder_set_geometries(
      SegmentAllocator allocator, MemorySegment self, MemorySegment coords, MemorySegment meta) {
    var mh$ = MltLayerEncoder_set_geometries.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("MltLayerEncoder_set_geometries", allocator, self, coords, meta);
      }
      return (MemorySegment) mh$.invokeExact(allocator, self, coords, meta);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class MltLayerEncoder_add_column {
    public static final FunctionDescriptor DESC =
        FunctionDescriptor.of(
            MltLayerEncoder_add_column_result.layout(),
            mlt_ffi_h.C_POINTER,
            DiplomatStringView.layout(),
            mlt_ffi_h.C_INT,
            DiplomatU8View.layout(),
            mlt_ffi_h.C_INT,
            DiplomatBoolView.layout());

    public static final MemorySegment ADDR =
        SYMBOL_LOOKUP.findOrThrow("MltLayerEncoder_add_column");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * MltLayerEncoder_add_column_result MltLayerEncoder_add_column(MltLayerEncoder *self, DiplomatStringView name, MltColumnType column_type, DiplomatU8View data, uint32_t count, DiplomatBoolView present)
   * }
   */
  public static FunctionDescriptor MltLayerEncoder_add_column$descriptor() {
    return MltLayerEncoder_add_column.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * MltLayerEncoder_add_column_result MltLayerEncoder_add_column(MltLayerEncoder *self, DiplomatStringView name, MltColumnType column_type, DiplomatU8View data, uint32_t count, DiplomatBoolView present)
   * }
   */
  public static MethodHandle MltLayerEncoder_add_column$handle() {
    return MltLayerEncoder_add_column.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * MltLayerEncoder_add_column_result MltLayerEncoder_add_column(MltLayerEncoder *self, DiplomatStringView name, MltColumnType column_type, DiplomatU8View data, uint32_t count, DiplomatBoolView present)
   * }
   */
  public static MemorySegment MltLayerEncoder_add_column$address() {
    return MltLayerEncoder_add_column.ADDR;
  }

  /**
   * {@snippet lang=c :
   * MltLayerEncoder_add_column_result MltLayerEncoder_add_column(MltLayerEncoder *self, DiplomatStringView name, MltColumnType column_type, DiplomatU8View data, uint32_t count, DiplomatBoolView present)
   * }
   */
  public static MemorySegment MltLayerEncoder_add_column(
      SegmentAllocator allocator,
      MemorySegment self,
      MemorySegment name,
      int column_type,
      MemorySegment data,
      int count,
      MemorySegment present) {
    var mh$ = MltLayerEncoder_add_column.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall(
            "MltLayerEncoder_add_column", allocator, self, name, column_type, data, count, present);
      }
      return (MemorySegment)
          mh$.invokeExact(allocator, self, name, column_type, data, count, present);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class MltLayerEncoder_add_string_column {
    public static final FunctionDescriptor DESC =
        FunctionDescriptor.of(
            MltLayerEncoder_add_string_column_result.layout(),
            mlt_ffi_h.C_POINTER,
            DiplomatStringView.layout(),
            DiplomatStringView.layout(),
            DiplomatU32View.layout(),
            DiplomatBoolView.layout());

    public static final MemorySegment ADDR =
        SYMBOL_LOOKUP.findOrThrow("MltLayerEncoder_add_string_column");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * MltLayerEncoder_add_string_column_result MltLayerEncoder_add_string_column(MltLayerEncoder *self, DiplomatStringView name, DiplomatStringView data, DiplomatU32View offsets, DiplomatBoolView present)
   * }
   */
  public static FunctionDescriptor MltLayerEncoder_add_string_column$descriptor() {
    return MltLayerEncoder_add_string_column.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * MltLayerEncoder_add_string_column_result MltLayerEncoder_add_string_column(MltLayerEncoder *self, DiplomatStringView name, DiplomatStringView data, DiplomatU32View offsets, DiplomatBoolView present)
   * }
   */
  public static MethodHandle MltLayerEncoder_add_string_column$handle() {
    return MltLayerEncoder_add_string_column.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * MltLayerEncoder_add_string_column_result MltLayerEncoder_add_string_column(MltLayerEncoder *self, DiplomatStringView name, DiplomatStringView data, DiplomatU32View offsets, DiplomatBoolView present)
   * }
   */
  public static MemorySegment MltLayerEncoder_add_string_column$address() {
    return MltLayerEncoder_add_string_column.ADDR;
  }

  /**
   * {@snippet lang=c :
   * MltLayerEncoder_add_string_column_result MltLayerEncoder_add_string_column(MltLayerEncoder *self, DiplomatStringView name, DiplomatStringView data, DiplomatU32View offsets, DiplomatBoolView present)
   * }
   */
  public static MemorySegment MltLayerEncoder_add_string_column(
      SegmentAllocator allocator,
      MemorySegment self,
      MemorySegment name,
      MemorySegment data,
      MemorySegment offsets,
      MemorySegment present) {
    var mh$ = MltLayerEncoder_add_string_column.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall(
            "MltLayerEncoder_add_string_column", allocator, self, name, data, offsets, present);
      }
      return (MemorySegment) mh$.invokeExact(allocator, self, name, data, offsets, present);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class MltLayerEncoder_encode {
    public static final FunctionDescriptor DESC =
        FunctionDescriptor.of(
            MltLayerEncoder_encode_result.layout(), mlt_ffi_h.C_POINTER, mlt_ffi_h.C_POINTER);

    public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("MltLayerEncoder_encode");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * MltLayerEncoder_encode_result MltLayerEncoder_encode(MltLayerEncoder *self, const MltEncoderConfig *config)
   * }
   */
  public static FunctionDescriptor MltLayerEncoder_encode$descriptor() {
    return MltLayerEncoder_encode.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * MltLayerEncoder_encode_result MltLayerEncoder_encode(MltLayerEncoder *self, const MltEncoderConfig *config)
   * }
   */
  public static MethodHandle MltLayerEncoder_encode$handle() {
    return MltLayerEncoder_encode.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * MltLayerEncoder_encode_result MltLayerEncoder_encode(MltLayerEncoder *self, const MltEncoderConfig *config)
   * }
   */
  public static MemorySegment MltLayerEncoder_encode$address() {
    return MltLayerEncoder_encode.ADDR;
  }

  /**
   * {@snippet lang=c :
   * MltLayerEncoder_encode_result MltLayerEncoder_encode(MltLayerEncoder *self, const MltEncoderConfig *config)
   * }
   */
  public static MemorySegment MltLayerEncoder_encode(
      SegmentAllocator allocator, MemorySegment self, MemorySegment config) {
    var mh$ = MltLayerEncoder_encode.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("MltLayerEncoder_encode", allocator, self, config);
      }
      return (MemorySegment) mh$.invokeExact(allocator, self, config);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class MltLayerEncoder_destroy {
    public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(mlt_ffi_h.C_POINTER);

    public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("MltLayerEncoder_destroy");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * void MltLayerEncoder_destroy(MltLayerEncoder *self)
   * }
   */
  public static FunctionDescriptor MltLayerEncoder_destroy$descriptor() {
    return MltLayerEncoder_destroy.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * void MltLayerEncoder_destroy(MltLayerEncoder *self)
   * }
   */
  public static MethodHandle MltLayerEncoder_destroy$handle() {
    return MltLayerEncoder_destroy.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * void MltLayerEncoder_destroy(MltLayerEncoder *self)
   * }
   */
  public static MemorySegment MltLayerEncoder_destroy$address() {
    return MltLayerEncoder_destroy.ADDR;
  }

  /**
   * {@snippet lang=c :
   * void MltLayerEncoder_destroy(MltLayerEncoder *self)
   * }
   */
  public static void MltLayerEncoder_destroy(MemorySegment self) {
    var mh$ = MltLayerEncoder_destroy.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("MltLayerEncoder_destroy", self);
      }
      mh$.invokeExact(self);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class MltTileEncoder_new {
    public static final FunctionDescriptor DESC = FunctionDescriptor.of(mlt_ffi_h.C_POINTER);

    public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("MltTileEncoder_new");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * MltTileEncoder *MltTileEncoder_new()
   * }
   */
  public static FunctionDescriptor MltTileEncoder_new$descriptor() {
    return MltTileEncoder_new.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * MltTileEncoder *MltTileEncoder_new()
   * }
   */
  public static MethodHandle MltTileEncoder_new$handle() {
    return MltTileEncoder_new.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * MltTileEncoder *MltTileEncoder_new()
   * }
   */
  public static MemorySegment MltTileEncoder_new$address() {
    return MltTileEncoder_new.ADDR;
  }

  /**
   * {@snippet lang=c :
   * MltTileEncoder *MltTileEncoder_new()
   * }
   */
  public static MemorySegment MltTileEncoder_new() {
    var mh$ = MltTileEncoder_new.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("MltTileEncoder_new");
      }
      return (MemorySegment) mh$.invokeExact();
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class MltTileEncoder_add_layer {
    public static final FunctionDescriptor DESC =
        FunctionDescriptor.of(
            MltTileEncoder_add_layer_result.layout(), mlt_ffi_h.C_POINTER, mlt_ffi_h.C_POINTER);

    public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("MltTileEncoder_add_layer");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * MltTileEncoder_add_layer_result MltTileEncoder_add_layer(MltTileEncoder *self, MltLayerEncoder *layer)
   * }
   */
  public static FunctionDescriptor MltTileEncoder_add_layer$descriptor() {
    return MltTileEncoder_add_layer.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * MltTileEncoder_add_layer_result MltTileEncoder_add_layer(MltTileEncoder *self, MltLayerEncoder *layer)
   * }
   */
  public static MethodHandle MltTileEncoder_add_layer$handle() {
    return MltTileEncoder_add_layer.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * MltTileEncoder_add_layer_result MltTileEncoder_add_layer(MltTileEncoder *self, MltLayerEncoder *layer)
   * }
   */
  public static MemorySegment MltTileEncoder_add_layer$address() {
    return MltTileEncoder_add_layer.ADDR;
  }

  /**
   * {@snippet lang=c :
   * MltTileEncoder_add_layer_result MltTileEncoder_add_layer(MltTileEncoder *self, MltLayerEncoder *layer)
   * }
   */
  public static MemorySegment MltTileEncoder_add_layer(
      SegmentAllocator allocator, MemorySegment self, MemorySegment layer) {
    var mh$ = MltTileEncoder_add_layer.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("MltTileEncoder_add_layer", allocator, self, layer);
      }
      return (MemorySegment) mh$.invokeExact(allocator, self, layer);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class MltTileEncoder_encode {
    public static final FunctionDescriptor DESC =
        FunctionDescriptor.of(
            MltTileEncoder_encode_result.layout(), mlt_ffi_h.C_POINTER, mlt_ffi_h.C_POINTER);

    public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("MltTileEncoder_encode");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * MltTileEncoder_encode_result MltTileEncoder_encode(MltTileEncoder *self, const MltEncoderConfig *config)
   * }
   */
  public static FunctionDescriptor MltTileEncoder_encode$descriptor() {
    return MltTileEncoder_encode.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * MltTileEncoder_encode_result MltTileEncoder_encode(MltTileEncoder *self, const MltEncoderConfig *config)
   * }
   */
  public static MethodHandle MltTileEncoder_encode$handle() {
    return MltTileEncoder_encode.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * MltTileEncoder_encode_result MltTileEncoder_encode(MltTileEncoder *self, const MltEncoderConfig *config)
   * }
   */
  public static MemorySegment MltTileEncoder_encode$address() {
    return MltTileEncoder_encode.ADDR;
  }

  /**
   * {@snippet lang=c :
   * MltTileEncoder_encode_result MltTileEncoder_encode(MltTileEncoder *self, const MltEncoderConfig *config)
   * }
   */
  public static MemorySegment MltTileEncoder_encode(
      SegmentAllocator allocator, MemorySegment self, MemorySegment config) {
    var mh$ = MltTileEncoder_encode.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("MltTileEncoder_encode", allocator, self, config);
      }
      return (MemorySegment) mh$.invokeExact(allocator, self, config);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }

  private static class MltTileEncoder_destroy {
    public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(mlt_ffi_h.C_POINTER);

    public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("MltTileEncoder_destroy");

    public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
  }

  /**
   * Function descriptor for:
   * {@snippet lang=c :
   * void MltTileEncoder_destroy(MltTileEncoder *self)
   * }
   */
  public static FunctionDescriptor MltTileEncoder_destroy$descriptor() {
    return MltTileEncoder_destroy.DESC;
  }

  /**
   * Downcall method handle for:
   * {@snippet lang=c :
   * void MltTileEncoder_destroy(MltTileEncoder *self)
   * }
   */
  public static MethodHandle MltTileEncoder_destroy$handle() {
    return MltTileEncoder_destroy.HANDLE;
  }

  /**
   * Address for:
   * {@snippet lang=c :
   * void MltTileEncoder_destroy(MltTileEncoder *self)
   * }
   */
  public static MemorySegment MltTileEncoder_destroy$address() {
    return MltTileEncoder_destroy.ADDR;
  }

  /**
   * {@snippet lang=c :
   * void MltTileEncoder_destroy(MltTileEncoder *self)
   * }
   */
  public static void MltTileEncoder_destroy(MemorySegment self) {
    var mh$ = MltTileEncoder_destroy.HANDLE;
    try {
      if (TRACE_DOWNCALLS) {
        traceDowncall("MltTileEncoder_destroy", self);
      }
      mh$.invokeExact(self);
    } catch (Error | RuntimeException ex) {
      throw ex;
    } catch (Throwable ex$) {
      throw new AssertionError("should not reach here", ex$);
    }
  }
}
